create database 'proba_lsac';
use 'proba_lsac';

create table contacts (id bigint generated by default as identity, email varchar(255), is_resolved boolean, message varchar(255), name varchar(255), primary key (id));
create table enrollments (id bigint generated by default as identity, student_id bigint, tutoring_class_id bigint, primary key (id));
create table reviews (id bigint not null, message varchar(255), user_id bigint not null, primary key (id));
create table tutoring_classes (id bigint generated by default as identity, description varchar(255), subject varchar(255), teacher_id bigint, primary key (id));
create table users (id bigint generated by default as identity, email varchar(255), firstname varchar(255), lastname varchar(255), password varchar(255), role integer, primary key (id));